language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: foxypost
  api_key:
    secure: gN7R+jeXnGYAacIThPF9j0n/Lt2Cwj+FL1SIxAlYyiDEwq+EYk/To+gJdZh/ZkED73rQkO8jHvie7TVC+tSjBrnO02L51jTwSR5LpeWbbCNTCrSLRjpzevshTi27nTMcNF1IJK4Nu3k2vBB3cOWnlEXJhYwirRC5sb/S1nUw9QMBLUDN0pWZ5Co7tNd4Fg+qPYG2ml5E3EKJKee9/n8S+xX2CMnpj7ZGiYZycNX+cvo3yUqd9FUJF9AIK349so+hJaELp7Hkc5ZWhPG3HjkfYRDrZBfdx1h8acBtZY9dB/G8Gh3VM6zAFBTtobBIYoHf4Hrk5GT7CWBL44HfN3mgV9kJyQDk2lOlfUSwskZLNgtQ5W8JFLdy+70+dZ7wzNPyadB69bQv3UMKpVGHamcUa8uPUnorkowW30HnN3kFVYKBBT/CqFT0j7x4aa7FgnIfbEtVssTyyHxcrWrZVx5lKx7k6SnFOVBUjilZPjZRXR2s9vMoaMZrROZ8XM45FAguc0ihAPAUsxCt+xq/TdA5RErav3ORwIqD5NSNOxzEnRAw57nIIg+kuViUXQ4Do3smPpA4uuT3nfxXPB4NFqZLCXxOczH8zSErcmAFs53LGl9zP/RGaImceorzjnoneDS018Kvh39kLMQL8nyFJ1k5N5El1uKJwzZ/158HVChEDw8=
