language: node_js
node_js:
  - "12"
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  app: Foxypost
  api_key:
    secure: LwU/Si+jsXLdA/rzrOasJN4wwkSeEtB8u2Nu41nFvEAHDCe/9PFlbbZKTpsN4GTVQooD1jctCtVSCfgCMcCBgtB1jlAuvQWGlBhWOxLvJ17Py1jH9OLY7tZemntsJh6GRPQd55eyQg1QtLNO/vurLFM4TGy7DKNfI22z/fw9f53jlnELqqscu8VrjsPbNqWwZ2Ar/A3zaQcCaI3oYwOjYhUy2f8DQbHkVDZl110XcCd5sfv0GC2nFuW24JHFPeYXfukbl+5pAFw2N8FG2NShU623vllE/AKyQJRvXlIxDp8JwIr+LvugQj7F55kjjQTYAUzKA/tUnKj7dIzzoHOnbc7LvuQomXvUf4J8drfCwGbFs2Q2P6CBz36yebYD6QiqPW08NJCHiebeHueK9n5MVbYYlHa3n9yiPPMvzsfCoRkhL4w3Mmh5OROtzPflqbl2Weuy7NI9h4V62JIVr0l0oz+f5qUMi3x5NTV4tjXpXB6am4nA5HkBd1pSlo6WBN+crqZ+J6+qufTJ4EL+Wz/Cu+3dNB/aupMZXtgB4u8F3awmPrQHEZRntktPSzOnVdIoWuZfG8fzp3MoGXS/F1H8oeK1xiDN9db2o/8TBPuQ07XMyFG3h/2fNR5NFbBuYQXd/doLe5CFrEzPbq+7BM3wCJHOhMCNbXP6EdLOvnF0EJ8=
